config/routes.rb
Twidder2::Application.routes.draw do

  root to: 'static_pages#home'
  
  match '/',        to: 'static_pages#home'
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/about_us', to: 'static_pages#about_us'

  resources :users do
    resources :answers 
  end

  resources :celebrities do
    resources :tweets
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :answer, :celebrity_id, :tweet, :celebrity, :answers, :url, :populatetweet, :post_regex
  belongs_to :celebrity
  has_many :answers
  serialize :answer, Array

  def self.populate
  	Celebrity.all.each do |celebrity|
  		PopulateTweet.new(celebrity).add_to_database
  	end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @celebrity = Celebrity.find(params[:celebrity_id])
    @tweets = @celebrity.tweets
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
    @celebrity = Celebrity.find(params[:celebrity_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new
    @celebrity = Celebrity.find(params[:celebrity_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
    @celebrity = Celebrity.find(params[:celebrity_id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @celebrity = Celebrity.find(params[:celebrity_id])
    @tweet = @celebrity.tweets.build(params[:tweet])
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to celebrity_tweet_path(@celebrity, @tweet), notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])
    @celebrity = Celebrity.find(params[:celebrity_id])
    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to celebrity_tweet_path, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @celebrity = Celebrity.find(params[:celebrity_id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to celebrity_tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for [@celebrity, @tweet] do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tweet
    = f.text_field :tweet
  .field
    = f.label :answer
    = f.text_field :answer
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', celebrity_tweets_path
\|
= link_to 'Back', celebrity_tweets_path(@celebrity)

app/views/tweets/index.html.haml
%h1 Listing tweets

%table
  %tr
    %th Celebrity
    %th Tweet
    %th Answer
    %th Url
    %th
    %th

  - @tweets.each do |tweet|
    %tr
      %td= tweet.celebrity_id
      %td= tweet.tweet
      %td= tweet.answer
      %td= tweet.url
      %td= link_to 'Show', celebrity_tweet_path(@celebrity, tweet)
      %td= link_to 'Edit', edit_celebrity_tweet_path(@celebrity, tweet)
      %td= link_to 'Destroy', celebrity_tweet_path(@celebrity, tweet), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tweet', new_celebrity_tweet_path(@celebrity)

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', celebrity_tweets_path(@celebrity)

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b Celebrity:
  = @tweet.celebrity_id
%p
  %b Tweet:
  = @tweet.tweet
%p
  %b Answer:
  = @tweet.answer
%p
  %b Id:
  = @tweet.id


= link_to 'Edit', edit_celebrity_tweet_path(@celebrity, @tweet)
\|
= link_to 'Back', celebrity_tweets_path(@celebrity)