config/routes.rb
Twidder2::Application.routes.draw do

  root to: 'static_pages#home'
  
  match '/',        to: 'static_pages#home'
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/about_us', to: 'static_pages#about_us'

  resources :users do
    resources :answers 
  end

  resources :celebrities do
    resources :tweets
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :score, :answers, :password_confirmation
  has_secure_password
  has_many :answers

  before_save { |user| user.email = email.downcase }
  before_create :create_remember_token

  validates :name, :presence => true, :format => {:with => /[a-z]/i, :message => "must only have letters"}, :length => { :minimum => 2, :message => "must have at least 2 characters" } 

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :format => {:with => VALID_EMAIL_REGEX},
  :uniqueness => true

  VALID_PASSWORD_REGEX = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/
  validates :password, :presence => true, :format => {:with => VALID_PASSWORD_REGEX, :message => "must include at least one upper case letter, one lower case letter, and one numeric digit"},:length =>{:within => 8..16,:message => "must be between 8 to 16 characters"}
  validates :password_confirmation, :presence => true
  after_validation { self.errors.messages.delete(:password_digest)}

  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

     respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to Twidder!"
        format.html { redirect_to @user }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated"
        sign_in @user
        format.html { redirect_to @user}
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:sucess] = "User destroyed"
    redirect_to users_url
  end

  private
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  / .field
  /   = f.label :score
  /   = f.number_field :score
  .actions
    = f.submit 'Create my account', class: "btn btn-large btn-primary"

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %><br/>
  Score <%= user.score %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Standings</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users.sort! { |a, b| b.score <=> a.score } %>
</ul>

<%= will_paginate %>

<!-- %h1 Listing users

%table
  %tr
    %th Name
    %th Password
    %th Score
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.password
      %td= user.score
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path
 -->

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Password
    %th Score
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.password
      %td= user.score
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <h1>
        Score: <%= @user.score %>
      </h1>
      <div class="usersshow">
        <li class="buttonz"><%=link_to "Edit", edit_user_path(@user) %></li>
      </div>
      <div class="usersshow">
        <li class="buttonz"><%=link_to "Standings", users_path %></li>
      </div>
      <div class="usersshow">
        <li class="buttonz"><%=link_to 'New Game', new_user_answer_path(@user, @answer) %></li>
      </div>
    </section>
  </aside>
</div>

<!-- 
%h1
  = gravatar_for @user
  = @user.name

%p#notice= notice

%p
  %b Name:
  = @user.name

/ %p
/   %b Password:
/   = @user.password

%p
  %b Score:
  = @user.score
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
/ = link_to 'Game', game_user_path(@user)
= link_to 'New Game', user_answers_path(@user, @answer)
/users/:user_id/answers -->