config/routes.rb
Twidder2::Application.routes.draw do

  root to: 'static_pages#home'
  
  match '/',        to: 'static_pages#home'
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/about_us', to: 'static_pages#about_us'

  resources :users do
    resources :answers 
  end

  resources :celebrities do
    resources :tweets
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/answer.rb
class GuessValidator < ActiveModel::Validator
  def validate(my_answer)
    my_tweet = Tweet.find(my_answer.tweet_id)
    if my_answer.guess.split(" ").length != my_tweet.tweet.split(" ").length
      my_answer.errors[:base] << "Your guess must have the same number of words as the tweet."
    end
  end
end

class Answer < ActiveRecord::Base
  attr_accessible :correct, :guess, :tweet_id, :user_id, :user, :tweet
  belongs_to :user
  belongs_to :tweet
	validates :guess, :presence => true, :length => { :maximum => 200, :message => "must have the same number of words as the tweet"}
  validates_with GuessValidator
  
  def rm_word_tweet(text)
    text.gsub(/tweet\S*/i, "")
    # "This is a tweet." => "This is a "
  end 

  def rm_hashtags(text)
    text.gsub(/#\S*/, "")
    # This guess #has a hashtag. => "This guess  a hashtag."
  end

  def rm_weird_characters(text)
    text.gsub(/[^\w.;?!,' -]/, "")
    # "This guess has a ♥ that's a heart."=> "This guess has a  that's a heart."
  end

  def rm_elipses(text)
    text.gsub(/[^\w\s]/, " ")
  end 

  def apply_regex(string)
    rm_weird_characters(rm_elipses(rm_hashtags(rm_word_tweet(string))))
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @user = User.find(params[:user_id])
    @answers = @user.answers
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])
    @user = User.find(params[:user_id])
    @tweet = Tweet.find(@answer.tweet_id)
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @tweet = Tweet.all.sample
    @answer = Answer.new
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
    @user = User.find(params[:user_id])
  end

  # POST /answers
  # POST /answers.json
  def create
    # debugger
    @user = User.find(params[:user_id])
    @tweet = Tweet.find(params[:answer][:tweet_id])
    @answer = @user.answers.build(params[:answer])
    regex_1 = @answer.apply_regex(@answer.guess)
    regex_2 = regex_1.gsub(/[^\w ']/, "") # removes all but numbers, letters, and ' <= those things
    regex_3 = regex_2.gsub(/(\d)/,"") # removes numbers
    my_answer = regex_3.split(" ") # => ["I", "love", "u"]
    index = 0
    if my_answer.length == @tweet.answer.length
      @answer.correct = true
      my_answer.each do |word|
        if !@tweet.answer[index].include?(word) # [["I"], ["love"], ["you", "urn", "your"]]
          @answer.correct = false
          break
        end 
        index += 1
      end
    end
    if @answer.correct
      @user.update_attribute(:score, @user.score + 1)
    end
    respond_to do |format|
      if @answer.save
        format.html { redirect_to user_answer_path(@user, @answer), notice: 'Answer was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])
    @user = User.find(params[:user_id])
    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to user_answer_path(@user, @answer), notice: 'Answer was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @user = User.find(params[:user_id])
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to user_answers_url }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= form_for [@user, @answer] do |f|
  - if @answer.errors.any?
    #error_explanation.error_explanation_for_answers_new
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_area :guess, :spellcheck => "false"
    = f.hidden_field :tweet_id, value: @tweet.id
  .submit
    = f.submit 'Correct Tweet', :class => "submitButton"

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', user_answers_path
\|
= link_to 'Back', user_answers_path(@user)

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Name: 
    %th Score:
    %tr
      %td= @user.name
      %td= @user.score


%table
  %tr
    %th Tweet
    %th Guess
    %th Correct
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= Tweet.find(answer.tweet_id).tweet
      %td= answer.guess
      %td= answer.correct
      %td= link_to 'Show', user_answer_path(@user, answer)
      / %td= link_to 'Edit', edit_user_answer_path(@user, answer)

%br

= link_to 'Play', new_user_answer_path(@user)

app/views/answers/new.html.haml
%h2
  Here is a tweet with at least one misspelling:
.celebritytweet{:align => "center"}
  %blockquote.twitter-tweet{:lang => "en"}
    %p= @tweet.tweet
    %a{:href => @tweet.url}link
  %script{:async => "", :charset => "utf-8", :src => "//platform.twitter.com/widgets.js"}
%br
%h2
  Can you correct it?
.fakeComposeTweet
  .top
    %p Compose Correction
  = render 'form'

.centerz
  .buttonz
    = link_to 'Back', user_answers_path(@user, @answer)
  .buttonz
    = link_to 'Skip', new_user_answer_path(@user, @answer)

app/views/answers/show.html.haml
.centerz
  .resultz
    %b Result:
    = @answer.correct == false ? "Sorry! The correct answer is: #{Gingerice::Parser.new.parse(@tweet.post_regex)["result"]}": "Correct!"
    .br
    %b Score:
    = "#{@user.score}"
%h2
  Here is the original tweet:
.realtweet{:align => "center"}
  %blockquote.twitter-tweet{:lang => "en"}
    %p= @tweet.tweet
    %a{:href => @tweet.url}link
  %script{:async => "", :charset => "utf-8", :src => "//platform.twitter.com/widgets.js"}
%br

%h2
  Here is your correction:
.fakeWidget
  .image
    = gravatar_for @user
  .followButton
    %a.twitter-follow-button{"data-show-count" => "false", "data-show-screen-name" => "false", :href => "https://twitter.com/twidder_app"}
      Follow @twidder_app
    :javascript
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  .name
    = @user.name
  .handle
    = @user.email
  .tweet
    = @answer.guess
  .line
  .time
    = @answer.created_at
  .icons
    .reply.icon.unclicked
      %i.fa.fa-reply
    .retweet.icon.unclicked
      %i.fa.fa-retweet
    .star.icon.unclicked
      %i.fa.fa-star
.br

.centerz
  .buttonz
    = link_to 'My Answers', user_answers_path(@user)
  .buttonz
    = link_to 'Play Again', new_user_answer_path(@user)
  .buttonz
    = link_to 'My Profile', user_path(@user)